services:
  trackera-nginx:
    image: mahmoudabdelrady/trackera-nginx:${TRACKERA_NGINX_VERSION:-latest}
    ports:
      - "127.0.0.1:3000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  trackera-backend:
    image: mahmoudabdelrady/trackera-backend:${TRACKERA_BACKEND_VERSION:-latest}
    environment:
      JAVA_OPTS: -Dspring.profiles.active=prod

      # Database
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # Email
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # App Config
      FRONTEND_URL: ${FRONTEND_URL}
      APP_BASE_URL: ${APP_BASE_URL}
      HASHER_SECRET_KEY: ${HASHER_SECRET_KEY}
      HASHER_ENCRYPTION_KEY: ${HASHER_ENCRYPTION_KEY}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_MAX_AGE: ${ACCESS_TOKEN_MAX_AGE}
      REFRESH_TOKEN_MAX_AGE: ${REFRESH_TOKEN_MAX_AGE}
      JOB_MAX_FAILURES: ${JOB_MAX_FAILURES}
      JOB_BATCH_PAGE_SIZE: ${JOB_BATCH_PAGE_SIZE}

      # OAuth2
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JIRA_CLIENT_ID: ${JIRA_CLIENT_ID}
      JIRA_CLIENT_SECRET: ${JIRA_CLIENT_SECRET}

      # RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      RABBITMQ_PREFETCH: ${RABBITMQ_PREFETCH}
      RABBITMQ_CONCURRENT_CONSUMERS: ${RABBITMQ_CONCURRENT_CONSUMERS}
      RABBITMQ_MAX_CONCURRENT_CONSUMERS: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS}
    healthcheck:
      test: ["CMD-SHELL", 'wget -qO- http://127.0.0.1:8080/actuator/health | grep -q ''"status":"UP"'' || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 90s

  trackera-frontend:
    image: mahmoudabdelrady/trackera-frontend:${TRACKERA_FRONTEND_VERSION:-latest}
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
