# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Email
trackera.mail.username=${MAIL_USERNAME}
trackera.mail.password=${MAIL_PASSWORD}

# Variables
trackera.frontend.url=${FRONTEND_URL}
trackera.app.base-url=${APP_BASE_URL}
trackera.hasher_secret_key=${HASHER_SECRET_KEY}
trackera.hasher.encryption_key=${HASHER_ENCRYPTION_KEY}
trackera.tokens.access=${ACCESS_TOKEN_SECRET}
trackera.tokens.refresh=${REFRESH_TOKEN_SECRET}

# OAuth2
trackera.oauth2.google.client-id=${GOOGLE_CLIENT_ID}
trackera.oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET}
trackera.oauth2.jira.client-id=${JIRA_CLIENT_ID}
trackera.oauth2.jira.client-secret=${JIRA_CLIENT_SECRET}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
trackera.rabbitmq.prefetch=${RABBITMQ_PREFETCH}
trackera.rabbitmq.concurrent-consumers=${RABBITMQ_CONCURRENT_CONSUMERS}
trackera.rabbitmq.max-concurrent-consumers=${RABBITMQ_MAX_CONCURRENT_CONSUMERS}

# Logging
logging.level.root=INFO
logging.level.com.mdevs.trackera=INFO
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
